version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
configuration: Release
before_build:
- cmd: nuget restore
build:
  project: Toggler.Tests/Toggler.Tests.csproj
  verbosity: normal
test:
  categories:
    only:
    - integration
